name: github-actions
on:
  push:
    branches:
    # Limit to the `master` branch
    - master
jobs:
  github-actions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run the workflow
      run: |
        set -x
        # Configure Git for the push from the workflow to the repository
        git config --global user.email "tomas@hubelbauer.net"
        git config --global user.name "Tomas Hubelbauer"
        # Check out the `master` branch because by default GitHub Actions checks out detached HEAD
        git checkout master
        # Run the render
        sudo snap install openscad-nightly
        Xvfb :5 -screen 0 800x600x24 &
        export DISPLAY=:5
        xvfb-run openscad-nightly -o model.png model.scad
        git add model.png
        # Commit the changes to the Git repository if any
        if git diff-index --quiet HEAD --; then
          exit
        fi
        git commit -m "Update the render"
        # Authenticate with GitHub using the out of the box workflow integration PAT
        git remote set-url origin https://tomashubelbauer:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}
        # Pull before pushing to integrate fast forward changes if any
        git pull --rebase
        # Push the rendered model to GitHub
        git push
